const E=Watchtower,$=id=>document.getElementById(id),key='watchtower-save-v1';let s=E.fresh(),selected=1,placing=null,paused=false,speed=1,carry=0,last=performance.now(),hiddenAt=0;
function report(seconds,before){$('reportText').innerHTML=`<p>${Math.floor(seconds/60)}분 ${Math.floor(seconds%60)}초 동안 거점이 운영되었습니다.</p><p>철강 변화 ${Math.floor(s.steel-before)>=0?'+':''}${Math.floor(s.steel-before)} · 현재 인구 ${s.people}명</p><p>${s.incident?'현장 이상 신호가 남아 있습니다. 시설을 직접 조사하세요.':'현재 접수된 현장 경보는 없습니다.'}</p><p>${s.tech?'배터리 기술 확보. 감시탑을 건설할 수 있습니다.':''}${s.core?' 북부 탐사대가 AI 코어를 회수했습니다.':''}</p><p>최근 통신: ${s.logs[0].text}</p>`;if(!$('report').open)$('report').showModal();}
let playing=false,slot=null,showRoutes=false;
try{const data=JSON.parse(localStorage.getItem(key));if(data?.state&&[1,2].includes(data.state.version)&&Array.isArray(data.state.buildings)&&data.state.buildings.every(b=>E.defs[b.type])&&Number.isFinite(data.at))slot=data;}catch{}
function titleUI(){ $('continueGame').disabled=!slot; $('slotInfo').textContent=slot?`거점 07 · 인구 ${slot.state.people}명 · ${Math.floor(slot.state.time/60)}분 운영 · 저장 ${new Date(slot.at).toLocaleString('ko-KR')}`:'저장된 거점이 없습니다. 새로운 불빛을 시작하세요.'; }
function startGame(fresh){if(fresh&&slot&&!confirm('기존 거점을 새 거점으로 교체할까요?'))return;const elapsed=!fresh&&slot?Math.min(1800,Math.max(0,Math.floor((Date.now()-slot.at)/1000))):0;s=fresh?E.fresh():E.migrate(JSON.parse(JSON.stringify(slot.state)));const before=s.steel;E.tick(s,elapsed);playing=true;paused=false;carry=0;selected=1;placing=null;last=performance.now();document.body.classList.remove('at-title');$('titleScreen').hidden=true;$('gameScreen').inert=false;$('pause').textContent='Ⅱ 일시정지';ui();save();if(elapsed>=30)report(elapsed,before);}
$('newGame').onclick=()=>startGame(true);$('continueGame').onclick=()=>{if(slot)startGame(false);};$('howTo').onclick=()=>{$('guide').hidden=!$('guide').hidden;};$('menu').onclick=()=>{save();playing=false;$('report').close();document.body.classList.add('at-title');$('titleScreen').hidden=false;$('gameScreen').inert=true;titleUI();};$('overlay').onclick=()=>{showRoutes=!showRoutes;$('overlay').classList.toggle('active',showRoutes);};$('assignment').onchange=e=>{E.act(s,'assign:'+e.target.value);ui();save();};titleUI();
function save(){if(!playing)return;try{slot={state:JSON.parse(JSON.stringify(s)),at:Date.now()};localStorage.setItem(key,JSON.stringify(slot));$('saveStatus').textContent='로컬 자동 저장 · 부재 진행 최대 30분';}catch{$('saveStatus').textContent='저장 불가 · 브라우저 저장 권한 확인';}}
function actionButton(label,action,disabled=false){return `<button class="action" data-action="${action}" ${disabled?'disabled':''}>${label}<span>↗</span></button>`;}
function ui(){const h=8+Math.floor(s.time/60);$('clock').textContent=`DAY ${1+Math.floor(h/24)} / ${String(h%24).padStart(2,'0')}:${String(s.time%60).padStart(2,'0')}`;$('resources').innerHTML=[['철강',`${Math.floor(s.steel)}/${E.capacity(s)}`],['원광',Math.floor(s.ore)],['냉각수',Math.floor(s.water)],['식량',Math.floor(s.food)],['거주 인원',`${s.people}/${E.count(s,'home')*10}`]].map(([a,b])=>`<span>${a}<b>${b}</b></span>`).join('');$('power').textContent=`전력 ${E.power(s)} / 수요 ${E.demand(s)}`;
 const objectives=s.contract.done?['물류 거점 확보 완료','납품 목표를 달성했습니다. 연구와 거점 전문화를 이어가세요.']:s.diplomacy?['북부 지역 확보','채굴장과 제련 공장을 연결하고 자유상단에 철강 120을 납품하세요.']:s.core?['어떤 문명을 만들 것인가','회수한 AI 코어의 처리 방침을 결정하세요.']:s.people>=15?['북부의 신호를 추적하라','탐사대를 보내 구세계 구조물을 조사하세요.']:s.stage>=2?['새로운 이웃을 맞이하라','거주동을 추가 건설하고 도착한 생존자들을 수용하세요.']:['거점의 불빛을 지켜라','시설을 관찰하세요. 이상 징후가 나타나면 현장을 클릭해 원인을 조사하세요.'];$('objective').textContent=objectives[0];$('objectiveText').textContent=objectives[1];
 const b=s.buildings.find(b=>b.id===selected),affected=b&&s.incident&&(s.incident.type==='coolant'?b.type==='power':b.type==='store'||b.type==='factory');$('detail').innerHTML=b?`<span class="tag">SECTOR ${b.x}–${b.y} / ${b.left?'CONSTRUCTION':affected?'ATTENTION':'ONLINE'}</span><h2>${E.defs[b.type].name}</h2><p>${b.left?`완공까지 ${b.left}초`:affected?({coolant:'냉각수 부족. 출력 저하로 생산과 연구가 느려집니다.',logistics:'채굴량이 운송량을 초과했습니다. 차량을 추가하거나 채굴장 가까이에 창고를 건설하세요.',fire:'적재 구역 화재. 방치하면 물자가 손실됩니다.'})[s.incident.type]:({power:'김도윤 · 전기 94 / 발전 설비 점검 중',store:'박민재 · 물류 81 / 운송 경로 관리 중',home:'생활 구역 · 10명 수용 / 공동 배급 운영',factory:'자동 제련 라인 · 전력 확보 시 철강 생산 증가',lab:'연구팀 · 전력 확보 시 연구 진행',tower:'알렉스 케인 · 전직 연합 장교 / 북부 경계 중',mine:'원광 채굴 · 가까운 창고와 차량 확보가 운송 효율을 결정합니다.'})[b.type]}</p>${affected&&s.incident.contained?'<p class=notice>AI가 응급 격리했습니다. 추가 손실은 멈췄지만 운영 제한이 남아 있습니다.</p>':''}${affected?actionButton(s.incident.type==='coolant'?'냉각수 공급 · 20 소모':`정비팀 파견 · 철강 ${s.assignment==='repair'?10:15}`,'resolve',s.incident.type==='coolant'?s.water<20:s.steel<(s.assignment==='repair'?10:15)):''}`:'<p>지도에서 시설을 선택하세요.</p>';
 $('orders').innerHTML=(s.refugees?actionButton('생존자 5명 수용','admit',E.count(s,'home')*10<s.people+5):'')+actionButton(s.expedition?`ALPHA 귀환까지 ${s.expedition}초`:s.discovered?'북부 구조물 발견 완료':'북부 탐사 · 식량 20','explore',s.people<15||s.expedition>0||s.discovered||s.food<20)+actionButton(s.tech?'배터리 기술 확보':s.research?`배터리 연구 ${s.research}초`:'배터리 연구 · 철강 40','research',!E.count(s,'lab')||s.tech||s.research>0||s.steel<40)+(s.core?actionButton('아르카에 양도 · 기술 / 철강 +40','arca')+actionButton('성역회의와 봉인 · 식량 +60','sanctuary'):'');
 $('news').innerHTML=`<p>중앙 폐허 / 독립 거점의 통신망이 복원되었습니다.</p><p>${s.discovered?'북부 황무지 / 인간과 다른 반복적 구조물이 관측되었습니다.':'북부 황무지 / 미확인 기계 신호. 탐사가 필요합니다.'}</p><p>아르카 신뢰 ${s.relations.arca} · 성역회의 신뢰 ${s.relations.sanctuary}</p>`;$('logs').innerHTML=s.logs.slice(0,8).map(l=>`<p><time>${Math.floor(l.time/60)}:${String(l.time%60).padStart(2,'0')}</time>${l.text}</p>`).join('');$('hint').textContent=placing?`${E.defs[placing].name} 배치 중 · 빈 구획을 클릭하세요 / Esc 취소`:s.incident?'△ 현장 이상 감지 · 경고등이 켜진 시설을 클릭해 조사하세요.':'시설을 클릭해 조사 · 운영 지시 후 다른 일을 해도 거점은 계속 움직입니다.';
 $('builds').innerHTML=Object.entries(E.defs).map(([id,d])=>`<button data-build="${id}" class="${placing===id?'active':''}" ${s.steel<d.cost||id==='tower'&&!s.tech?'disabled':''}>${d.name}<small>${id==='tower'&&!s.tech?'배터리 연구 필요':`철강 ${d.cost} · ${d.time}초`}</small></button>`).join('');$('policy').value=s.policy; networkUI();}
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]'),b=e.target.closest('[data-build]');if(a){E.act(s,a.dataset.action);ui();save();}if(b){placing=placing===b.dataset.build?null:b.dataset.build;ui();}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){placing=null;ui();}});$('policy').onchange=e=>{s.policy=e.target.value;save();};$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'▶ 운영 재개':'Ⅱ 일시정지';};$('speed').onclick=()=>{speed=speed===1?5:speed===5?15:1;$('speed').textContent=speed+'× 속도';};$('away').onclick=()=>{const before=s.steel;E.tick(s,300);report(300,before);ui();save();};$('closeReport').onclick=()=>$('report').close();$('reset').onclick=()=>{if(confirm('저장된 거점을 지우고 새로 시작할까요?')){s=E.fresh();selected=1;placing=null;carry=0;ui();save();}};
document.addEventListener('visibilitychange',()=>{if(!playing)return;if(document.hidden){hiddenAt=Date.now();save();}else if(hiddenAt){const elapsed=paused?0:Math.min(1800,Math.floor((Date.now()-hiddenAt)/1000)),before=s.steel;E.tick(s,elapsed);hiddenAt=0;last=performance.now();if(elapsed>=30)report(elapsed,before);ui();save();}});window.addEventListener('pagehide',save);
const canvas=$('map'),ctx=canvas.getContext('2d');let w=0,h=0,unit=30,ox=0,oy=0;function point(x,y){return {x:ox+(x-y)*unit,y:oy+(x+y)*unit*.5};}function poly(points,fill,stroke){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}}
function diamond(x,y,color,stroke){poly([point(x,y),point(x+1,y),point(x+1,y+1),point(x,y+1)],color,stroke);}
function block(x,y,z,color){const a=point(x,y),b=point(x+.85,y),c=point(x+.85,y+.85),d=point(x,y+.85);poly([b,c,{x:c.x,y:c.y-z},{x:b.x,y:b.y-z}],'#263938','#50665b');poly([c,d,{x:d.x,y:d.y-z},{x:c.x,y:c.y-z}],'#304744','#52675c');poly([a,b,c,d].map(p=>({x:p.x,y:p.y-z})),color,'#718374');}
function draw(now){const rect=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;if(w!==rect.width||h!==rect.height){w=rect.width;h=rect.height;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);}unit=Math.min(w/26,(h-230)/13);ox=w*.5;oy=h*.27;ctx.clearRect(0,0,w,h);const grad=ctx.createRadialGradient(w*.5,h*.5,20,w*.5,h*.5,w*.7);grad.addColorStop(0,'#2b3833');grad.addColorStop(1,'#101c20');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);
 for(let x=-3;x<15;x++)for(let y=-3;y<15;y++){const inside=x>=0&&x<=10&&y>=0&&y<=10,road=x===5||y===5;diamond(x,y,inside?(road?'#3b4540':(x+y)%2?'#2a3832':'#2d3b34'):'#1c2a27',inside?'#415048':'#25352e');if(!inside&&Math.abs(x*13+y*7)%9===0)block(x+.2,y+.2,8+Math.abs(x+y)%15,'#3a4740');}
 drawRoutes(); const sorted=[...s.buildings].sort((a,b)=>a.x+a.y-b.x-b.y);for(const b of sorted){const p=point(b.x+.45,b.y+.45),danger=s.incident&&(s.incident.type==='coolant'?b.type==='power':['store','factory'].includes(b.type));if(b.id===selected||placing)diamond(b.x,b.y,b.id===selected?'#819365':'#3e5340','#c4d6a2');const z=b.type==='tower'?65:b.type==='power'?32:24;block(b.x+.08,b.y+.08,b.left?Math.max(4,z*(1-b.left/E.defs[b.type].time)):z,b.left?'#8b7952':danger?'#956e51':({power:'#91a190',store:'#aa9d7a',home:'#648c87',factory:'#929580',lab:'#87a9af',tower:'#b1ba9d',mine:'#a18b6f'})[b.type]);if(b.type==='power'&&!b.left){ctx.save();ctx.translate(p.x,p.y-z-3);ctx.rotate(now*.002*(danger?3:1));ctx.strokeStyle='#d3e4c6';ctx.lineWidth=3;for(let k=0;k<3;k++){ctx.rotate(Math.PI*2/3);ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(12,0);ctx.stroke();}ctx.restore();}if(!b.left){ctx.fillStyle=danger?'#f8a46d':'#cee4a3';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=12;ctx.fillRect(p.x-8,p.y-7,4,3);ctx.shadowBlur=0;}if(danger){for(let j=0;j<5;j++){const phase=(now*.0004+j*.2)%1;ctx.fillStyle=`rgba(179,161,133,${.5*(1-phase)})`;ctx.beginPath();ctx.arc(p.x+Math.sin(j+phase*3)*8,p.y-z-phase*55,3+phase*10,0,Math.PI*2);ctx.fill();}ctx.fillStyle='#f4b080';ctx.font='bold 18px Segoe UI';ctx.fillText('!',p.x+20,p.y-z-8);}ctx.textAlign='center';ctx.font='10px Segoe UI,Malgun Gothic';ctx.fillStyle='#dee5cd';ctx.fillText(E.defs[b.type].name,p.x,p.y+24);if(b.left){ctx.fillStyle='#d6b776';ctx.fillRect(p.x-18,p.y+30,36*(1-b.left/E.defs[b.type].time),3);}}
 for(let i=0;i<s.people;i++){const t=(now*.000045*(i%3+1)+i*.137)%1,p=i%2?point(5.4,t*10):point(t*10,5.4);ctx.fillStyle=i%5===0?'#d2ad78':'#cad6b8';ctx.fillRect(p.x,p.y,i%5===0?8:3,i%5===0?4:5);}if(s.expedition){const p=point(9,0);ctx.strokeStyle='#bcd4a0';ctx.beginPath();ctx.arc(p.x,p.y,10+now*.012%20,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#d3deb6';ctx.fillText('ALPHA ↗',p.x,p.y-25);}ctx.textAlign='left';ctx.fillStyle='#899d89';ctx.font='10px Segoe UI';ctx.fillText('N ↗  북부 황무지',w-150,h-180);}
canvas.onclick=e=>{const r=canvas.getBoundingClientRect(),dx=(e.clientX-r.left-ox)/unit,dy=(e.clientY-r.top-oy)/(unit*.5),x=Math.floor((dx+dy)/2),y=Math.floor((dy-dx)/2);if(placing){if(E.build(s,placing,x,y)){selected=s.buildings.at(-1).id;placing=null;save();}else {ui();$('hint').textContent='배치 불가 · 도로(5행/5열)와 기존 시설을 피하고 자원을 확인하세요.';return;}}else{let best=null,dist=55;for(const b of s.buildings){const p=point(b.x+.45,b.y+.45),d=Math.hypot(e.clientX-r.left-p.x,e.clientY-r.top-(p.y-12));if(d<dist){best=b;dist=d;}}if(best)selected=best.id;}ui();};
let refresh=0,saveTimer=0;function frame(now){const dt=Math.min(2,(now-last)/1000);last=now;if(playing&&!document.hidden&&!paused){carry+=dt*speed;const n=Math.floor(carry);if(n){E.tick(s,n);carry-=n;}}if(now-refresh>500){ui();refresh=now;}if(now-saveTimer>10000&&!document.hidden){save();saveTimer=now;}if(playing)draw(s.time*1000+carry*1000);requestAnimationFrame(frame);}ui();requestAnimationFrame(frame);

function networkUI(){const m=E.metrics(s);$('assignment').value=s.assignment;$('network').innerHTML=`<div class="section-title">생산·물류 관제</div><p>채굴 ${m.rate.toFixed(2)}/초 → 운송 ${m.hauling.toFixed(2)}/초 → 제련 ${(m.production*m.supply).toFixed(2)}/초</p><p>현장 적재 ${Math.floor(s.raw)} / 150 · 원광 ${Math.floor(s.ore)}<br>화물차 ${s.trucks}대 · ${s.shipment?`입고 ${s.shipment.left}초 후 / 원광 ${Math.floor(s.shipment.amount)}`:'운송 대기'}<br>설비 부담 ${Math.round(s.strain)} / 240 · 직원 피로 ${Math.round(s.fatigue)}%</p><p class="notice">${m.noisy?'주거 인근 산업 소음으로 피로가 증가합니다. 시설은 주거에서 3칸 이상 떨어뜨리세요.':m.rate>m.hauling?'운송 능력 부족: 차량 증차 또는 채굴장 인근 창고가 필요합니다.':!E.count(s,'mine')?'채굴장을 건설해 원광 공급을 시작하세요.':!E.count(s,'factory')?'제련 공장을 건설해 원광을 철강으로 전환하세요.':m.supply<1?'전력 부족: 생산 25%, 연구 정지. 발전소를 추가하세요.':'물류 흐름 안정. 생산과 계약 납품을 준비하세요.'}</p>${actionButton('화물차 추가 · 철강 35','truck',s.steel<35||s.trucks>=6)}${actionButton(s.throttle?'정상 생산으로 전환':'감산 가동 · 과열 완화','throttle')}${actionButton(s.maintenance?'예방 정비 해제':'예방 정비 · 철강 1 / 30초','maintenance')}${!s.cooling?actionButton('예비 냉각 설치 · 철강 35','cooling',s.steel<35):'<p>예비 냉각 계통 설치 완료</p>'}${s.contract.done?'<p class="tag">자유상단 계약 완료 · 물류 거점 확보</p>':s.contract.accepted?actionButton(`철강 120 납품 · 남은 ${s.contract.left}초`,'deliver',s.steel<120):actionButton('자유상단 계약 · 보상 식량 / 차량','contract')}<p>거점 방향: ${{independent:'독립',arca:'자동화 · 제련 +25%',sanctuary:'공동체 · 식량 생산 증가'}[s.specialization]}</p>`;}
function drawRoutes(){const routes=E.routes(s);for(const route of routes){if(!route.to)continue;const a=point(route.from.x+.5,route.from.y+.5),b=point(route.to.x+.5,route.to.y+.5);if(showRoutes){ctx.strokeStyle=route.from.type==='mine'?'#deb36e':'#89cbd2';ctx.setLineDash([4,5]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([]);}if(route.from.type==='mine'&&s.shipment){const t=1-s.shipment.left/s.shipment.total;ctx.fillStyle='#efc483';ctx.fillRect(a.x+(b.x-a.x)*t-4,a.y+(b.y-a.y)*t-3,9,6);}}}
