const {test}=require('node:test');const assert=require('node:assert/strict');const E=require('../engine.js');
test('tutorial chains into housing, expedition, diplomacy',()=>{const s=E.fresh();E.tick(s,30);assert.equal(s.incident.type,'coolant');assert.ok(E.act(s,'resolve'));E.tick(s,20);assert.ok(s.refugees);assert.equal(E.act(s,'admit'),false);assert.ok(E.build(s,'home',7,6));E.tick(s,30);assert.ok(E.act(s,'admit'));assert.equal(s.people,15);assert.ok(E.act(s,'explore'));E.tick(s,120);assert.ok(s.core);assert.ok(E.act(s,'arca'));assert.equal(s.relations.arca,25);assert.equal(s.relations.sanctuary,-15);assert.equal(E.act(s,'sanctuary'),false);});
test('construction rejects collisions, bounds, funds and locked tech',()=>{const s=E.fresh();assert.equal(E.build(s,'home',3,3),false);assert.equal(E.build(s,'tower',2,2),false);assert.equal(E.build(s,'home',-1,1),false);assert.equal(E.build(s,'home',2.5,2),false);s.steel=0;assert.equal(E.build(s,'home',2,2),false);});
test('safe AI contains incidents and leaves repair to player',()=>{const s=E.fresh();s.policy='safe';E.tick(s,95);assert.ok(s.incident.contained);assert.equal(s.resolved,0);assert.ok(E.act(s,'resolve'));assert.equal(s.incident,null);const manual=E.fresh();E.tick(manual,95);assert.ok(!manual.incident.contained);});
test('offline simulation matches repeated ticks and respects storage',()=>{const a=E.fresh(),b=E.fresh();E.tick(a,1800);for(let i=0;i<1800;i++)E.tick(b,1);assert.deepEqual(a,b);assert.ok(a.steel>=0&&a.steel<=E.capacity(a));});
test('research requires power and unlocks construction after completion',()=>{const s=E.fresh();s.stage=3;s.nextEvent=99999;s.buildings.push({id:4,type:'lab',x:7,y:7,left:0});assert.ok(E.act(s,'research'));s.incident={type:'coolant',at:0};E.tick(s,20);assert.equal(s.research,90);E.act(s,'resolve');E.tick(s,90);assert.equal(s.tech,true);s.steel=100;assert.ok(E.build(s,'tower',8,8));});

function industrial(x=7,y=3){const s=E.fresh();s.stage=3;s.maintenance=true;s.buildings.push({id:4,type:'mine',x,y,left:0},{id:5,type:'factory',x:7,y:4,left:0});return s;}
test('shorter routes deliver more ore and trucks relieve backlog',()=>{const near=industrial(),far=industrial(1,9);E.tick(near,240);E.tick(far,240);assert.ok(near.totalDelivered>far.totalDelivered);far.steel=150;E.act(far,'truck');E.act(far,'truck');const before=far.totalDelivered;E.tick(far,120);assert.ok(far.totalDelivered-before>20);});
test('factory consumes ore, cannot conjure it, maintenance prevents fire',()=>{const s=industrial();s.ore=0;s.raw=0;s.buildings=s.buildings.filter(b=>b.type!=='mine');const before=s.steel;E.tick(s,10);assert.ok(s.steel-before<1);E.tick(s,400);assert.equal(s.incident,null);const stressed=industrial();stressed.maintenance=false;E.tick(stressed,245);assert.equal(stressed.incident.type,'fire');});
test('safe containment prevents continued loss while unresolved fire stops factory',()=>{const s=industrial();s.policy='safe';s.incident={type:'fire',at:0};E.tick(s,90);assert.ok(s.incident.contained);const ore=s.ore;E.tick(s,100);assert.ok(s.ore>=ore);assert.equal(s.resolved,0);});
test('contracts award once and expire without silently consuming steel',()=>{const s=E.fresh();assert.ok(E.act(s,'contract'));assert.ok(E.act(s,'deliver'));assert.equal(s.trucks,2);assert.equal(E.act(s,'deliver'),false);const other=E.fresh();E.act(other,'contract');E.tick(other,360);assert.equal(other.contract.accepted,false);assert.equal(E.act(other,'deliver'),false);});
test('assignments change costs and research speed',()=>{const s=E.fresh();s.incident={type:'fire',at:0};s.steel=10;assert.ok(E.act(s,'resolve'));assert.equal(s.steel,0);s.research=10;E.act(s,'assign:research');E.tick(s,5);assert.ok(s.tech);assert.equal(E.act(s,'assign:unknown'),false);});
test('migration preserves original progress and road cells are protected',()=>{const s=E.fresh();s.version=1;s.steel=87;delete s.trucks;E.migrate(s);assert.equal(s.steel,87);assert.equal(s.trucks,1);assert.equal(E.build(s,'mine',5,2),false);});
